#!/usr/bin/with-contenv bash

сreate_catalog_for_variable() {
  
  local value=${!1}
  if [ -z "$value" ]; then
    echo "Не установлена переменная: $1" >&2
    exit 1
  fi
  if [ ! -d "$value" ]; then
    mkdir -p "$value" || {
        echo "Ошибка создания каталога: $value" >&2
        exit 1
    }
    
  fi

}

addpath () {
  x="$1"
  IFS=:
  set -- $PATH
  IFS=
  while test "$#" -gt 0 ; do
    if test "$1" = "$x" ; then
      return
    fi
    shift
  done
  PATH="${x}:$PATH"
}

echo "**** CATALOGS CREATION FOR TESTING ****"

сreate_catalog_for_variable "EDT_PATH_WORKSPACE"
сreate_catalog_for_variable "CI_PROJECT_DIR"
сreate_catalog_for_variable "PROJECT_BULD_DIR"
сreate_catalog_for_variable "PROJECT_LOG_DIR"
сreate_catalog_for_variable "DB_PATH"

echo "**** SETTINGS OF THE ENVIRONMENT ****"

export _1C_HOME=$(dirname "$(find "/opt/1cv8/" -name "1cv8" -type f)")
export JAVA_HOME=$(dirname "$(find "/opt/1C/1CE/components" -name "java" -type f)")
export EDT_HOME=$(dirname "$(find "/opt/1C/1CE/components" -name "1cedtcli" -type f)")
export RING_HOME=$(dirname "$(find "/opt/1C/1CE/components" -name "ring" -type f)")

echo "SET ENVIRONMENT VARIABLES: 
_1C_HOME=${_1C_HOME}
EDT_HOME=${EDT_HOME}
JAVA_HOME=${JAVA_HOME}
RING_HOME=${RING_HOME}
PATH=${PATH}
"

# Определение ALIAS
alias_str=("1cedtcli")
if [[ -n ${EDT_PATH_WORKSPACE} ]] ; then
    alias_str+=("-data ${EDT_PATH_WORKSPACE}")
else
    echo "Не задан путь для переменной \${EDT_PATH_WORKSPACE}. Операция прервана"
    exit 1
fi
# Максимальное время выполнения в секундах
if [[ -n ${EDT_MAXTIMEOUT} ]] ; then
    alias_str+=("-timeout ${EDT_MAXTIMEOUT}")
fi

if [[ -n ${EDT_VMARGS} ]] ; then
    alias_str+=("-vmargs ${EDT_VMARGS}")
fi

IFS=' ' # разделитель
alias cliedt='${alias_str[*]}'

# Настройка параметров запуска edt по-умолчанию
sed -i "s/^\(-Xmx\).*$/\1${EDT_MEMORY_LIMIT}/" "$EDT_HOME/1cedt.ini"

# Создание ссылок 
ln -s "${_1C_HOME}/1cv8" /usr/local/sbin/1cv8
ln -s "${_1C_HOME}/ibsrv" /usr/local/sbin/ibsrv
ln -s "${_1C_HOME}/ibcmd" /usr/local/sbin/ibcmd

ln -s "${RING_HOME}/ring" /usr/local/bin/ring
ln -s "${JAVA_HOME}/java" /usr/local/bin/java
ln -s "${EDT_HOME}/1cedtcli" /usr/local/bin/1cedtcli
ln -s "${EDT_HOME}/1cedt" /usr/local/bin/1cedt

cat <<EOF >> /etc/bash.bashrc
  # Глобальные переменные
  export _1C_HOME="${_1C_HOME}"
  export EDT_HOME="${EDT_HOME}"
  export RING_HOME="${RING_HOME}"
  export JAVA_HOME="${JAVA_HOME}"
  export PATH=${PATH}
  
  # Подключение библиотек сборок
  if [ -d \$CLI_LIB_PATH ]; then
    for i in "\${CLI_LIB_PATH}"/*.sh; do
      chmod +x "\$i"
      if [ -x "\$i" ] && [ ""\$i"" != *"test_"* ]; then
        . "\$i"
      fi
    done
    unset i
  fi

  IFS=' ' # разделитель
  alias cliedt='${alias_str[*]}'
EOF