#!/command/with-contenv bash

: <<'DOCUMENTATION'
Название: cli-download
Назначение: Анализирует переданный путь к файлу.
            Если в имени файла содержится протокол транспорта http://, https://, ftp://, sftp:// и т.д.
            Файл скачивается с ресурса для локального доступа.
Требования:
  - Нет

Использование:
    #!/bin/bash
    cli-download <URL или путь>                 # Загрузка в текущую директорию с сохранением имени
    cli-download <URL или путь> [Путь к файлу]  # Загрузка файла по указанному пути

Возвращаемые коды:
  0 - успех
  1 - ошибка операции

DOCUMENTATION

# Подключение общих библиотек
source ${CLI_LIB_PATH}/lib/cli-logger 

# Функция для проверки, начинается ли строка с поддерживаемого протокола
has_supported_protocol() {
    local url="$1"
    # Проверяем наличие протоколов через регулярное выражение
    if [[ "$url" =~ ^(http|https|ftp|sftp|ftps):// ]]; then
        return 0  # true
    else
        return 1  # false
    fi
}

# Основная логика скрипта
main() {

    # Проверяем, передан ли аргумент
    if [ $# -eq 0 ]; then
        error "Не указан путь для анализа."
        info "Использование: $0 \"<URL или путь> к файлу\""
        exit 1
    fi

    local url="$1"
    local output_file="${2:-$(pwd)/${url##*/}}"

    # Проверяем, есть ли в строке поддерживаемый протокол
    if has_supported_protocol "$url"; then
        info "Обнаружен внешний ресурс: $url"
        info "Запуск загрузки..."

        if command -v curl &> /dev/null; then
            curl -J -L -o "$output_file" "$url"
        else
            error "Не найдена утилита curl для скачивания."
            exit 1
        fi

        # Проверяем код возврата последней команды
        if [ $? -eq 0 ]; then
            info "Файл сохранен: ${output_file}}"
            info "Скачивание завершено успешно."
        else
            error "Ошибка при скачивании файла."
            exit 1
        fi
    else
        info "Путь не содержит внешнего ресурса."
    fi

    exit 0
    
}

# Запуск основной функции
main "$@"
